- name: Set up other servers to process
  set_fact:
    my_address: "{{ansible_default_ipv4.address}}"
 
#- name: Debug data
#  debug: msg="{{ glusternodes | my_address}}"


#- name: Set up other servers to process 
#  set_fact:
#    other_servers: "{{ lookup('template', 'lookup.j2') | from_yaml }}"

#- name: Debug data
#  debug: msg="addresses to use {{ other_servers | join(',') }}"

- name: Ensure GlusterFS is installed.
  apt:
    name: "{{ item }}"
    state: installed
    force: yes
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: Ensure Gluster brick and mount directories exist.
  file: "path={{ item }} state=directory mode=0775"
  with_items:
     - "{{ gluster_brick_dir }}"
     - "{{ gluster_mount_dir }}"

- name: Configure Gluster volume.
  gluster_volume:
    state: present
    name: "{{ gluster_brick_name }}"
    brick: "{{ gluster_brick_dir }}"
#   replicas: "{{ gluster_replicas_number }}"
    cluster: "{{ glusternodes }}"
    force: yes
  run_once: true

- name: Ensure Gluster volume is mounted.
  mount:
    name: "{{ gluster_mount_dir }}"
    src: "{{ inventory_hostname }}:/{{ gluster_brick_name }}"
    fstype: glusterfs
    opts: "defaults,_netdev"
    state: mounted
