---
  - name: swarm agent container
    docker:
      name: swarm
      image: swarm
      command: "join --advertise={{ansible_default_ipv4.address}}:{{docker_deamon_port}} consul://{{ consul_address }}:8500"
      ports:
        - "2375"
      net: host
      state: reloaded
      restart_policy: always
      restart_policy_retry: 3

