---
  - name: Ensure that consul DNS search domain is added
    lineinfile: dest=/etc/resolvconf/resolv.conf.d/head  line="search consul" state=present create=yes

  - name: Adding Docker apt key
    apt_key:
      keyserver=pgp.mit.edu
      id=58118E89F3A912897C070ADBF76221572C52609D

  - name: Configure docker repository
    lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present create=yes

  - name: install pip
    apt: name={{ item }} state=present update_cache=yes force=yes
    with_items:
        - docker-engine
        - python-pip

  - name: Install docker-py
    pip: name=docker-py version=1.2.3

  - name: Ensure Docker service is running
    service:
      name=docker
      state=started

