---
  - name: Adding Docker apt key
    apt_key:
        keyserver=pgp.mit.edu
        id=58118E89F3A912897C070ADBF76221572C52609D

  - name: Configure docker repository
    lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present create=yes
  
  - name: Set docker deamon opts - cluster
    set_fact:
      docker_deamon_opts: "{{ docker_deamon_options_cluster }}"
      when: docker_deamon_cluster == 'true'

  - name: Set docker deamon opts - standard
    set_fact:
      docker_deamon_opts: "{{ docker_deamon_options_standard }}"
      when: docker_deamon_cluster != 'true' or docker_deamon_cluster is not defined 

  - name: Configure Docker Opts
    lineinfile: 'dest=/etc/default/docker line="DOCKER_OPTS=\"{{ docker_deamon_opts }}\"" state=present create=no backrefs=yes regexp="(^|#)DOCKER_OPTS.*"'
    register: dockerDeamonOpts 
     
  - name: Restart docker deamon due to OPTs change
    service: name=docker state=restarted enabled=yes
    when: dockerDeamonOpts.changed

  - name: install pip
    apt: name={{ item }} state=present update_cache=yes force=yes
    with_items:
        - docker-engine
        - python-pip
        
  - name: Install docker-py
    pip: name=docker-py version=1.2.3

  - name: Ensure Docker service is running
    service:
        name=docker
        state=started

