---

- name: Check if consul exists 
  stat: "path=/usr/local/bin/consul" 
  register: consul_is_installed

- name: Download consul
  get_url: "url=http://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip dest=/usr/local/bin/consul.zip"
  register: consul_is_downloaded
  when: consul_is_installed.stat.exists != True

- name: Unpack consul file
  unarchive: "src=/usr/local/bin/consul.zip  dest=/usr/local/bin copy=no"
  when: consul_is_downloaded is defined and consul_is_installed.stat.exists != True 

- name: Create directories
  file: "path={{ item }}  state=directory"
  with_items:
   - "{{consul_ui_dir}}"                     # directory for UI
   - "{{consul_data_dir}}"                   # directory to hold data
   - "/etc/consul.d"                # configurations directory
   - "/etc/ansible/facts.d"                  # custom facts directory

- name: download consul UI 
  get_url: url=http://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_web_ui.zip dest=/tmp/consul_ui.zip
  when: consul_ui == true  

- name: Unpack consul UI file
  unarchive: "src=/tmp/consul_ui.zip  dest=/data-local/consul-ui copy=no"
  when: consul_ui == true

- name: Remove left over file 
  shell: "rm -f /usr/local/bin/consul.zip"
  when: consul_is_downloaded is defined

- name: install custom fact module for consule
  template:  "src=local_facts_consul.sh.j2 dest=/etc/ansible/facts.d/consul.fact mode=0755"

- name: reload ansible_local
  setup: filter=ansible_local

- name: Create upstart
  template: "src=upstart_consul.j2 dest=/etc/init/consul.conf owner=root group=root mode=u=rw,g=rw,o=r"

- name: Create config file - server
  template: "src=bootstrap.j2 dest=/etc/consul.d/consul.json owner=root group=root mode=u=rw,g=rw,o=r"

- name: Ensure service is running
  service: "name=consul state=started"

- name: Remove dnsmasq
  apt: name=dnsmasq state=absent force=yes
 
